spring:
  datasource:
    url: jdbc:mysql://${paip.datasource.ip}:3306/paip?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: ${paip.datasource.username}
    password: ${paip.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 文件上传设置
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 500MB
      max-request-size: 1024MB

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.indusec.file.model
  global-config:
    db-config:
      id-type: INPUT
paip:
  # 文件service
  file-server:
    #oss配置
    type: s3
    s3:
      endpoint: ${paip.s3.endpoint}
      access-key: ${paip.s3.access-key}
      accessKeySecret: ${paip.s3.accessKeySecret}
      bucketName: ${paip.s3.bucketName}
  # API文档服务
  swagger:
    enabled: true
    title: 文件服务
    description: 文件服务接口文档
    version: 1.0
    base-package: com.indusec.file.controller
  #多租户配置
  tenant:
    enable: true