spring:
  datasource:
    url: jdbc:mysql://${paip.datasource.ip}:3306/paip?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: ${paip.datasource.username}
    password: ${paip.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.indusec.common.model
  global-config:
    db-config:
      id-type: assign_id

paip:
  swagger:
    enabled: true
    title: 用户服务
    description: 用户服务接口文档
    version: 3.0
    base-package: com.indusec.user.controller
  # 设置过期时间(单位秒)
  cache-manager:
    configs:
      - key: menu
        second: 300
      - key: user
        second: 1800
  #多租户配置
  tenant:
    enable: true
    ignoreTables:
      - sys_user
      - sys_role_user
      - sys_role_menu
    ignoreSqls:
      # 用户关联角色时，显示所有角色
      - com.indusec.user.mapper.SysRoleMapper.findAll
      # 用户列表显示用户所关联的所有角色
      - com.indusec.user.mapper.SysUserRoleMapper.findRolesByUserIds
  #审计日志
  audit-log:
    enabled: true
    log-type: logger
#    log-type: db
#    datasource:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      jdbc-url: jdbc:mysql://${paip.datasource.ip}:3306/paip?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
#      username: ${paip.datasource.username}
#      password: ${paip.datasource.password}